name: Deploy Main to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # Or your desired Ruby version
          bundler-cache: true

      # This step assumes you have a Gemfile in your test branch root
      - name: Install Jekyll and dependencies
        run: |
          bundle config --local path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Build Jekyll site
        run: |
          # Ensure the output directory is clean before building
          rm -rf output
          bundle exec jekyll build -d output

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Use the standard GITHUB_TOKEN
          publish_dir: ./output # Directory containing the built site
          publish_branch: gh-pages # Target branch for deployment
          # Recommended: Set a commit message
          # commit_message: ${{ github.event.head_commit.message }}
          # Optional: Force push to overwrite history (use with caution)
          # force_orphan: true